### ISSUE TITLE
Support for PCRE

### ISSUE THREAD

**Issue by guettli** [drmikehenry/findx#7]
Hi,

If I understood the README, then you wrap `find` and `grep`.

This means PCRE regular expressions are not supported, right?

BTW, I am looking for a tool which gives my PCRE for the well known shell tools like find, grep, cut ...

Do you know a tool which could help?

**Comment by drmikehenry** [comment]
Hi, guettli,

Perl-compatible regular expressions are supported if your ``grep`` utility supports them.  For example, if you are running Linux, you almost certainly have GNU ``grep``, in which case you can switch to PCRE mode using the ``-P`` switch:
```sh
# Search for consecutive digits:
$ ffg -P '\d+'
```

If you always want the ``-P`` switch, you can add it using the ``findx`` config file.  By default, the arguments passed to GNU ``grep`` are as follows:
```sh
$ findx -show-var gnu_grep_args
gnu_grep_args = '-H' '--color=auto'
```

To append ``-P``, add the following line to your config file (on Linux, this would be ``~/.config/findx/config``; see ``findx --help`` for more details):
```
# Always use PCRE with GNU grep:
gnu_grep_args =+ '-P'
```

The ``'-P'`` is now appended to the arguments passed to GNU ``grep`` by default:
```sh
$ findx -show-var gnu_grep_args
gnu_grep_args = '-H' '--color=auto' '-P'
```

If you are not running Linux, your ``grep`` command may not be GNU ``grep``, but if you can install GNU ``grep`` in addition to your system grep, you can still use PCRE with ``findx``.  You can use the ``findx`` configuration variable ``gnu_grep`` to point to your newly installed GNU ``grep`` binary by either using an absolute path to the executable or specifying the name of the executable and placing the directory containing GNU ``grep`` in the system ``PATH``; in the latter case, you may want to name the GNU ``grep`` executable ``gnugrep`` to avoid collision with your system ``grep``.

**Comment by guettli** [comment]
Python has great PCRE regular expression. I think calling `grep` very often will slow down the search since creating subprocesses over and over again will cause load on the operating system. It depends, but I guess there are usec ases where Python without subprocesses is faster then C (like grep) with a log of subprocesses

**Comment by drmikehenry** [comment]
``findx`` has a well-defined purpose to reduce the amount of typing necessary to use the ``find`` utility correctly in its typical use cases, including launching external utilities like ``xargs`` and ``grep``.  By using ``xargs`` to launch these extra processes, the number of spawned processes is kept sufficiently low relative to the amount of work done per process.  On a typical Linux machine, around 128 KB of file paths are passed to each invocation of ``grep``.  For example, searching the 500 MB worth of files in the Linux kernel source tree yields only 10 invocations of ``grep``.  In addition, there is an automatic parallelization of work between ``find`` and ``grep`` which tends to speed the overall search speed as compared with ``grep -R`` by itself.

Regarding the use of Python (or Perl) as the regex engine, I have my doubts that it would ever achieve the same kind of raw performance that can be had with a tool like ``grep`` that's written in a compiled language and which is dedicated to raw search speed.  Regardless, adding such a feature directly to ``findx`` is outside the scope of my plans.

If you are looking purely for PRCE, it's hard to be more Perl compatible than the ``ack``[1] utility which is written in Perl.  If you really want it to be implemented in Python, there is ``grin``[2].

But if you are looking for raw search speed, there are other tools designed as a replacement for recursive ``grep`` invocations.  One such new tool, a relative newcomer to the field that is written in Rust, is ``ripgrep``[3].  It's web page includes some benchmarks comparing the speed of various tools, and as you can see ``ack`` is at least an order of magnitude slower than the compiled competition.  I routinely use The Silver Searcher, the second-place speed contender on that page, as part of my Vim configuration.  I tried an early version of ``ripgrep`` and thought it held promise for the future; I haven't tried it recently, so it might already be very usable for your needs.

If you don't want to use ``grep -P`` for your PCRE needs, then perhaps ``findx`` isn't the right tool for you; but hopefully one of the above dedicated search tools will fit your needs better.

[1]: https://beyondgrep.com/
[2]: https://pypi.python.org/pypi/grin/
[3]: https://github.com/BurntSushi/ripgrep

**Comment by guettli** [comment]
Thank you very much for this long explanation. I need to support some old linux distributions. These don't have "grep -P" up to now :-(

The tool grin looks a bit dated. No update since 7 years ..

All my questions are answered. I close this issue. Thank you for your support.
